
#service

server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
#datesource
spring:
  datasource:
    url: jdbc:mysql:///xmfh?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: admin
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  
    
#spring log
logging:
  level:
    com.cy: DEBUG
#mybatis
mybatis:
  configuration:
    caches:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/sys/*.xml

  