
#service

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
#datesource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmfh?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: admin
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html

  main:
    banner-mode: console
    
  
    
#spring log
logging:
  level:
    com.cy: DEBUG
#mybatis
mybatis:
  configuration:
    caches:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/sys/*.xml
#  
#mybatis-plus:
# # type-aliases-package: com.jt.pojo
#  mapper-locations: classpath:mapper/sys/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

  